<form action="/city/addcity/<?= $this->county_id ?>/" method="post">
<!--<p>County:</p><input type="text" name="county" id="county" value="<?= $this->county_id ?>" readonly=true><br>-->
<p>County:</p><input type="text" name="county" id="county" value="<?= $this->countyName ?>" readonly=true><br>
<p>Add new city:</p>
<input type="text" name="city" id="city" class="cityField">
<input type="hidden" name="county_id" value="<?= $this->county_id ?>">
<input type="submit" value="Add"><br><br>
<a href="/city/list/<?= $this->county_id ?>">GO BACK</a>
</form>


<style>
    form{
        text-align: center;
        margin-top:50px;
    }
    
    .counties,td{
        margin-top:10px;
        margin-left:10px;
    }
    
    #county{
        background: gray;
    }
</style>