<html>
    <body>      
        <form action="/county/AddCounty" method="post">
        <p>Add new county:</p>
        <input type="text" name="county" id="county" class="countyField">
        <input type="submit" value="Add"><br>
        </form>
        
<style>
    form{
        text-align: center;
        margin-top:50px;
    }
    
    .counties,td{
        margin-top:10px;
        margin-left:10px;
    }
</style>

    </body>
</html>