<div class ="container container1">
    <div class="row">
        <div class="col-md-6 col-md-offset-5"><a href="/county/AddCounty" id="addCounty" class="btn btn-primary">Add new county</a></div>
        <div class="col-md-8 col-md-offset-2">
            <table class="table table-bordered">
            <?php foreach ($this->result as $county): ?>
                <tr>
                    <td class="col-md-4 inner"><a href="/county/edit/<?= $county['id'] ?>" id='<?php $county['id']?>'><?= $county['name']?></a></td>
                    <td class="col-md-4 inner"><a href="/city/list/county/<?= $county['id'] ?>" id='<?php $city['id']?>'>List of citites</a></td>
                    <td class="col-md-1 inner"><a href="/county/delete/<?= $county['id'] ?>" id='<?php $county['id']?>' class="btn btn-danger">Delete</a></td>
                </tr>
            <?php endforeach ?>
                                            <a href="/county/edit/<?= 9999 ?>" id='<?php 9999 ?>'><?= 'I do not exist'?></a>
            </table>
        </div> <!-- end of row -->
    </div>
</div> <!-- end of container -->

<style>
    #addCounty{
        margin-bottom: 20px;
    }
    
    body{
        /*background-image: url('https://images2.alphacoders.com/688/68870.jpg');*/
        background-image: url("/images/mzkHacc.png");
    }
    
    .table{
        border: double;
    }
</style>
    